package br.com.changefsm.models;

public enum UpdateSMType {
	
	//ENUM
	ADD_STATE, REMOVE_STATE,
	//IF OR ELSE
	ADD_GUARD, REMOVE_GUARD, UPDATE_GUARD,
	//ASSIGNMENT OR METHOD CALL(but just those cases are same type to both)
	ADD_TRANSITION, REMOVE_TRANSITION, UPDATE_TRANSITION, 
	//SCAPE RETURN
	ADD_COMPOSITE_STATE, ALTER_BODY_COMPOSITE_STATE, REMOVE_COMPOSITE_STATE,
	//METHOD CALL
	REMOVE_ACTION, UPDATE_ACTION, ADD_ACTION,
	ADD_DOACTION_STATE, REMOVE_DOACTION_STATE, UPDATE_DOACTION_STATE, 
	ADD_EXITACTION_STATE, REMOVE_EXITACTION_STATE, UPDATE_EXITACTION_STATE,
	ADD_ENTRYACTION_STATE, REMOVE_ENTRYACTION_STATE, UPDATE_ENTRYACTION_STATE,
	//METHOD
	ADD_EVENT, REMOVE_EVENT;

}
