package br.com.changefsm.models;

public enum UpdateSMType {
	
	//ENUM
	ADD_STATE, REMOVE_STATE,
	//IF OR ELSE
	ADD_GUARD, REMOVE_GUARD, UPDATE_GUARD,
	//ASSIGNMENT OR METHOD CALL(but just those cases are same type to both)
	ADD_TRANSITION, REMOVE_TRANSITION, UPDATE_TRANSITION, 
	//SCAPE RETURN
	ADD_COMPOSITE_STATE, ALTER_BODY_COMPOSITE_STATE, REMOVE_COMPOSITE_STATE,
	//METHOD CALL
	ADD_ACTION_STATE, REMOVE_ACTION_STATE, UPDATE_ACTION_STATE;

}
